export const namespace = {
  CREATE_PRODUCER: 'CREATE_PRODUCER',
  CREATE_COFFEESHOP: 'CREATE_COFFEESHOP',
  UPDATE_USER: 'UPDATE_USER',
  GET_USER: 'GET_USER',

  GET_PRODUCER: 'GET_PRODUCER',
  GET_ALL_PRODUCERS: 'GET_ALL_PRODUCERS',

  GET_COFFEESHOP: 'GET_COFFEESHOP',
  GET_ALL_COFFEESHOPS: 'GET_ALL_COFFEESHOPS',

  GET_ALL_COFFEES: 'GET_ALL_COFFEES',
  GET_COFFEE: 'GET_COFFEE',
  CREATE_COFFEE: 'CREATE_COFFEE',

  CREATE_TRANSACTION: 'CREATE_TRANSACTION',
  GET_TRANSACTION: 'GET_TRANSACTION',
  GET_ALL_TRANSACTIONS: 'GET_ALL_TRANSACTIONS',

  EOS_USER_UPSERT: 'EOS_USER_UPSERT',
  EOS_COFFEE_UPSERT: 'EOS_COFFEE_UPSERT',
  EOS_COFFEE_GET: 'EOS_COFFEE_GET',
  EOS_SALE_INITIATE: 'EOS_SALE_INITIATE',
  EOS_SALE_GET: 'EOS_SALE_GET',
  EOS_SALE_SHIPPED: 'EOS_SALE_SHIPPED',
  EOS_SALE_DELIVERED: 'EOS_SALE_DELIVERED',

  SCATTER_STORE_EOS_CLIENT: 'SCATTER_STORE_EOS_CLIENT',
  SCATTER_STORE_IDENTITY: 'SCATTER_STORE_IDENTITY',
  SCATTER_STORE_SCATTER: 'SCATTER_STORE_SCATTER',
  SCATTER_LOGIN: 'SCATTER_LOGIN'
};
