export const namespace = {
  GET_PRODUCER: 'GET_PRODUCER',
  CREATE_PRODUCER: 'CREATE_PRODUCER',
  UPDATE_PRODUCER: 'UPDATE_PRODUCER',

  GET_COFFEESHOP: 'GET_COFFEESHOP',
  CREATE_COFFEESHOP: 'CREATE_COFFEESHOP',
  UPDATE_COFFEESHOP: 'UPDATE_COFFEESHOP',

  GET_ALLCOFFEES: 'GET_ALLCOFFEES',
  GET_COFFEE: 'GET_COFFEE',
  CREATE_COFFEE: 'CREATE_COFFEE',
}