export const namespace = {
  CREATE_PRODUCER: 'CREATE_PRODUCER',
  CREATE_COFFEESHOP: 'CREATE_COFFEESHOP',
  UPDATE_USER: 'UPDATE_USER',
  GET_USER: 'GET_USER',

  GET_PRODUCER: 'GET_PRODUCER',
  GET_ALL_PRODUCERS: 'GET_ALL_PRODUCERS',

  GET_COFFEESHOP: 'GET_COFFEESHOP',
  GET_ALL_COFFEESHOPS: 'GET_ALL_COFFEESHOPS',

  GET_ALL_COFFEES: 'GET_ALL_COFFEES',
  GET_COFFEE: 'GET_COFFEE',
  CREATE_COFFEE: 'CREATE_COFFEE'
};
